-- AlterTable: Add executionToken and leaseExpiresAt to PublicationSchedule
ALTER TABLE "PublicationSchedule" ADD COLUMN IF NOT EXISTS "executionToken" TEXT;
ALTER TABLE "PublicationSchedule" ADD COLUMN IF NOT EXISTS "leaseExpiresAt" TIMESTAMP(3);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "PublicationSchedule_status_leaseExpiresAt_idx" ON "PublicationSchedule"("status", "leaseExpiresAt");

-- System technical actor support with strictly scoped tenant isolation
CREATE OR REPLACE FUNCTION current_actor() RETURNS text LANGUAGE sql STABLE SET search_path = public, pg_temp AS $$
  SELECT COALESCE(
    (SELECT id FROM "User" WHERE id = nullif(current_setting('app.user_id', true), '') AND active),
    CASE WHEN current_setting('app.user_id', true) = 'system:scheduler' THEN 'system:scheduler' ELSE NULL END
  )
$$;

CREATE OR REPLACE FUNCTION can_read_client(org text, client text) RETURNS boolean LANGUAGE sql STABLE SET search_path = public, pg_temp AS $$
  SELECT (
    current_setting('app.user_id', true) = 'system:scheduler'
    AND current_setting('app.scheduler_org_id', true) = org
    AND current_setting('app.scheduler_client_id', true) = client
  ) OR EXISTS (
    SELECT 1 FROM "Membership" m JOIN "Organization" o ON o.id = m."organizationId"
    WHERE m."organizationId" = org AND m."userId" = current_actor() AND m.active AND o.active
      AND ((m."clientId" IS NULL AND m.role IN ('OWNER','ADMIN')) OR m."clientId" = client)
  )
$$;

CREATE OR REPLACE FUNCTION can_interact_post(org text, client text) RETURNS boolean LANGUAGE sql STABLE SET search_path = public, pg_temp AS $$
  SELECT (
    current_setting('app.user_id', true) = 'system:scheduler'
    AND current_setting('app.scheduler_org_id', true) = org
    AND current_setting('app.scheduler_client_id', true) = client
  ) OR can_edit_client(org, client) OR EXISTS (
    SELECT 1 FROM "Membership" m JOIN "Organization" o ON o.id = m."organizationId"
    WHERE m."organizationId" = org AND m."clientId" = client AND m."userId" = current_actor() AND m.active AND o.active AND m.role = 'APPROVER'
  )
$$;

-- Allow reading audit logs generated by system:scheduler for schedules and attempts in authorized clients
DROP POLICY IF EXISTS audit_read ON "AuditLog";
CREATE POLICY audit_read ON "AuditLog" FOR SELECT TO socialflow_runtime USING (
  can_manage("organizationId") OR ("actorUserId" = current_actor() AND (
    can_read_client("organizationId", "entityId") OR
    EXISTS (SELECT 1 FROM "Brand" b WHERE b.id = "AuditLog"."entityId" AND b."organizationId" = "AuditLog"."organizationId" AND can_read_client(b."organizationId", b."clientId")) OR
    EXISTS (SELECT 1 FROM "MediaAsset" m WHERE m.id = "AuditLog"."entityId" AND m."organizationId" = "AuditLog"."organizationId" AND can_read_client(m."organizationId", m."clientId")) OR
    EXISTS (SELECT 1 FROM "ContentBatch" cb WHERE cb.id = "AuditLog"."entityId" AND cb."organizationId" = "AuditLog"."organizationId" AND can_read_client(cb."organizationId", cb."clientId")) OR
    EXISTS (SELECT 1 FROM "Post" p WHERE p.id = "AuditLog"."entityId" AND p."organizationId" = "AuditLog"."organizationId" AND can_read_client(p."organizationId", p."clientId")) OR
    EXISTS (SELECT 1 FROM "SocialAccount" sa WHERE sa.id = "AuditLog"."entityId" AND sa."organizationId" = "AuditLog"."organizationId" AND can_read_client(sa."organizationId", sa."clientId")) OR
    EXISTS (SELECT 1 FROM "PublicationAttempt" pa WHERE pa.id = "AuditLog"."entityId" AND pa."organizationId" = "AuditLog"."organizationId" AND can_read_client(pa."organizationId", pa."clientId")) OR
    EXISTS (SELECT 1 FROM "PublicationSchedule" ps WHERE ps.id = "AuditLog"."entityId" AND ps."organizationId" = "AuditLog"."organizationId" AND can_read_client(ps."organizationId", ps."clientId"))
  )) OR (
    "actorUserId" = 'system:scheduler' AND (
      EXISTS (SELECT 1 FROM "PublicationSchedule" ps WHERE ps.id = "AuditLog"."entityId" AND ps."organizationId" = "AuditLog"."organizationId" AND can_read_client(ps."organizationId", ps."clientId")) OR
      EXISTS (SELECT 1 FROM "PublicationAttempt" pa WHERE pa.id = "AuditLog"."entityId" AND pa."organizationId" = "AuditLog"."organizationId" AND can_read_client(pa."organizationId", pa."clientId"))
    )
  )
);

-- Allow system:scheduler to read its scoped active Organization
DROP POLICY IF EXISTS organization_read ON "Organization";
CREATE POLICY organization_read ON "Organization" FOR SELECT TO socialflow_runtime USING (
  active AND (
    (current_setting('app.user_id', true) = 'system:scheduler' AND current_setting('app.scheduler_org_id', true) = "Organization".id)
    OR EXISTS (SELECT 1 FROM "Membership" m WHERE m."organizationId" = "Organization".id AND m."userId" = current_actor() AND m.active)
  )
);
